### ISSUE TITLE
Will this really work?? KDE mb air 7.2

### ISSUE THREAD

**Issue by Darwinoot** [c---/applesmc-next#4]
I'm really interested in this but i'm new to github. There doesn't seem to be any other options. How sure are you there won't be any issues?

**Comment by c---** [comment]
This uses the existing functionality that Apple built in to the firmware (by simply setting an SMC variable). I have been using it on an Air 7,2 for years.

It's stable, the only issues have been when breaking changes are introduced by the mainline kernel. These show up when trying to compile the module.

With that said, I would like to get as much testing as possible from people with various hardware before I send patches for the official kernel. Which is why I have been waiting years. :)

**Comment by SirLouen** [comment]
I'm using this on a Macbook Air 5,2 with Fedora's KDE spin. 

It works fine.

What kind of issues you may find? If you find issues report them here as expected. What's the point of opening an issue without a issue already found?
